### ISSUE TITLE
vtable for esphome

### ISSUE THREAD

**Issue by SHHA24** [esphome/issues#2586]
### The problem

Update to ESPhome ver. 2021.10.0
now getting the following error when trying to update device. 

undefined reference to `vtable for esphome::bme680_bsec::BME680BSECComponent'

### Which version of ESPHome has the issue?

2021.10.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP8266

### Board

Wemos D1 mini

### Component causing the issue

bsec-bme680

### Anything in the logs that might be useful for us?

```txt
Linking /data/airq/.pioenvs/airq/firmware.elf
/data/cache/platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: /data/airq/.pioenvs/airq/src/main.cpp.o:(.text.setup+0xe0): undefined reference to `vtable for esphome::bme680_bsec::BME680BSECComponent'
collect2: error: ld returned 1 exit status
*** [/data/airq/.pioenvs/airq/firmware.elf] Error 1
========================= [FAILED] Took 81.71 seconds =========================
```

**Comment by mwolter805** [comment]
Ran into a similar issue when updating from 2021.10.2 to 2021.10.3 but for the uptime component. Unfortunately didn't grab the full error but it included "undefined reference to vtable".

Deleteing the full device config directory (rm -rfv /<PATH_TO_ESPHOME>/config/<DEVICE_NAME>) resolved the issue. Appears clicking the three vertical dots for the device in the UI and selecting "Clean Build Files" could also work.

**Comment by mmakaay** [comment]
That sounds awfully familiar. The root cause issue was solved in this PR:
https://github.com/esphome/esphome/pull/2403

Using the current release version, I can compile the component without these errors.
@jsuanet also tried in a minute ago and reported success.

Please try the suggestion as done by @mwolter805
Another idea could be to make a copy of the YAML file, change the esphome name in it and then compile that one (using the download firmware option for the install for example). That would give us a fully clean build for sure. If that works, then it's clear that your current device build is wrecked.

**Comment by SHHA24** [comment]
Hi , I deleted the config and all core related files, but there must have been one I missed as still same issue. I deleted it again and uploaded a new config under a different name and copied the config settings but left the new name in place. 
this works now with the new name. 
thanks for help.

**Comment by mmakaay** [comment]
You're welcome, glad to hear that you got it worked out this way.
