### ISSUE TITLE
pb_decode.h and car_server.pb.h missing in 2025.8.0-dev (build from July 11)

### ISSUE THREAD

**Issue by top-gun** [esphome/issues#7229]
### The problem

My ESPHome project fails to compile with the latest `dev` build (2025.8.0-dev, released on July 11). The errors are:

src/esphome/components/tesla_ble_vehicle/log.cpp:7:10: fatal error: car_server.pb.h: No such file or directory
src/esphome/components/tesla_ble_vehicle/tesla_ble_vehicle.cpp:5:10: fatal error: pb_decode.h: No such file or directory

### What works

- The same project compiles fine with:
  - `2025.7.0-b1`
  - Earlier builds of `2025.8.0-dev` (prior to July 11)

This strongly suggests a regression in the latest dev version.

### Expected behavior

ESPHome should correctly:
1. Include the NanoPB library headers (e.g., `pb_decode.h`)
2. Generate or recognize protobuf header/source files (e.g., `car_server.pb.h` and `car_server.pb.c`) if `.proto` files are used in the project

### Steps to reproduce

1. Use the latest `dev` build of ESPHome (`2025.8.0-dev`, from July 11)
2. Compile a project with a custom component using Protocol Buffers (e.g. `car_server.proto` → `car_server.pb.h`)
3. Observe compilation failure due to missing headers

### Version

```yaml
esphome version: 2025.8.0-dev (fails)
last working version: 2025.7.0-b1 (works)




### Which version of ESPHome has the issue?

2025.8.0-dev build of july 11th

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2025.7.1

### What platform are you using?

ESP32-IDF

### Board

ESP32-Devkit-C

### Component causing the issue

custom component: tesla_ble_vehicle

### YAML Config

```yaml
substitutions:
  # all substitutions for this project
  friendly_name: "Tesla BLE F549C4"
  device_name: "tesla-ble-f549c4"
  ble_mac_address: !secret ble_mac_address
  tesla_vin: !secret tesla_vin

esp32:
  board: esp32dev  # set as needed for your board
  framework:
    type: esp-idf

api:
  encryption:
    key: !secret api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.178.128

external_components:
  source: github://top-gun/esphome-tesla-ble-test@2025.7

packages:
  base:  github://top-gun/esphome-tesla-ble-test/packages/base.yml@2025.7
  common: github://top-gun/esphome-tesla-ble-test/packages/common.yml@2025.7
  project: github://top-gun/esphome-tesla-ble-test/packages/project.yml@2025.7
  client: github://top-gun/esphome-tesla-ble-test/packages/client.yml@2025.7
  # listener: github://PedroKTFC/esphome-tesla-ble/packages/listener.yml # Uncomment this to scan find your VIN BLE MAC address

esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  libraries:
    - https://github.com/PedroKTFC/tesla-ble.git#dev 

tesla_ble_vehicle:
# At the time of writing, these are set to the default values. If you require a different value, uncomment and edit the value
#  update_interval: 2s # Base polling interval, used for VCSEC sensors
#  post_wake_poll_time: 300 # How long to poll for data after car awakes (s)
#  poll_data_period: 60 # Normal period when polling for data when not asleep (s)
#  poll_charging_period: 2 # Period to poll for data when charging (s)
#  poll_asleep_period: 60 # Period to poll for data when asleep (s)
  update_interval: 3s
  fast_poll_if_unlocked: 0

switch:
  - platform: gpio
    name: "Relais WB"
    pin: GPIO16
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2025.8.0-dev
INFO Reading configuration /config/esphome/tesla-wb.yaml...
INFO Detected timezone 'Europe/Berlin'
INFO Generating C++ source...
INFO Compiling app...
Processing tesla-ble-f549c4 (board: esp32dev; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.50302.0 (5.3.2) 
 - tool-cmake @ 3.30.2 
 - tool-esptoolpy @ 4.8.6 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.10.2 
 - tool-riscv32-esp-elf-gdb @ 14.2.0+20240403 
 - tool-xtensa-esp-elf-gdb @ 14.2.0+20240403 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp-elf @ 13.2.0+20240530
Reading CMake configuration...
[nanopb] No generation needed.
[nanopb] No generation needed.
Dependency Graph
|-- noise-c @ 0.1.10
Compiling .pioenvs/tesla-ble-f549c4/src/esphome/components/tesla_ble_vehicle/log.cpp.o
Compiling .pioenvs/tesla-ble-f549c4/src/esphome/components/tesla_ble_vehicle/tesla_ble_vehicle.cpp.o
Compiling .pioenvs/tesla-ble-f549c4/src/esphome/components/version/version_text_sensor.cpp.o
src/esphome/components/tesla_ble_vehicle/log.cpp:7:10: fatal error: car_server.pb.h: No such file or directory

*****************************************************************************
* Looking for car_server.pb.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:car_server.pb.h"
* Web  > https://registry.platformio.org/search?q=header:%1B%5Bm%1B%5BKcar_server.pb.h
*
*****************************************************************************

    7 | #include <car_server.pb.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
Compiling .pioenvs/tesla-ble-f549c4/src/esphome/components/wifi/wifi_component.cpp.o
*** [.pioenvs/tesla-ble-f549c4/src/esphome/components/tesla_ble_vehicle/log.cpp.o] Error 1
src/esphome/components/tesla_ble_vehicle/tesla_ble_vehicle.cpp:5:10: fatal error: pb_decode.h: No such file or directory

*************************************************************************
* Looking for pb_decode.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:pb_decode.h"
* Web  > https://registry.platformio.org/search?q=header:%1B%5Bm%1B%5BKpb_decode.h
*
*************************************************************************

    5 | #include <pb_decode.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/tesla-ble-f549c4/src/esphome/components/tesla_ble_vehicle/tesla_ble_vehicle.cpp.o] Error 1
```

### Verified

Manually installing the commit just before the suspected change: (on a Windows-PC that I use for testing)

pip install git+https://github.com/esphome/esphome.git@fc59c088001c0ea8208167cef0c0c5b95929a13b

→ Compilation works perfectly again.

Thiindicates the regression was introduced in:
https://github.com/esphome/esphome/commit/a240f0af901ac0727b6c116ea62438c47cb4a6af

**Comment by top-gun** [comment]
The same happens with the build from July 12th:

<img width="1840" height="1287" alt="Image" src="https://github.com/user-attachments/assets/04425ce0-b558-4381-85a7-d2a290a306ec" />

**Comment by top-gun** [comment]
Fixed by https://github.com/PedroKTFC/tesla-ble/pull/5 - our code had a faulty platform definition that caused the linker to abort. Thank you for the fast PR!
