### ISSUE TITLE
wake-word-voice-assistants/esp32-s3-box-3 compilation failure

### ISSUE THREAD

**Issue by ijc** [esphome/issues#6461]
### The problem

After upgrading to 2024.11.0 my project using https://github.com/esphome/wake-word-voice-assistants/blob/main/esp32-s3-box-3/esp32-s3-box-3.yaml is failing to build with:
```
Generating assembly for .pioenvs/esp32-s3-box-3-059d20/duer_profile.S
Compiling .pioenvs/esp32-s3-box-3-059d20/src/esphome/components/api/api_connection.o
Compiling .pioenvs/esp32-s3-box-3-059d20/src/esphome/components/api/api_frame_helper.o
Compiling .pioenvs/esp32-s3-box-3-059d20/src/esphome/components/api/api_pb2.o
Compiling .pioenvs/esp32-s3-box-3-059d20/src/esphome/components/api/api_pb2_service.o
In file included from src/esphome/components/voice_assistant/voice_assistant.h:16,
                 from src/esphome/components/api/api_connection.cpp:22:
src/esphome/components/speaker/speaker.h:13:10: fatal error: esphome/components/audio/audio.h: No such file or directory
 #include "esphome/components/audio/audio.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/esp32-s3-box-3-059d20/src/esphome/components/api/api_connection.o] Error 1
```

### Which version of ESPHome has the issue?

2024.11.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2024.11.2

### What platform are you using?

ESP32-IDF

### Board

m5stack Atom echo

### Component causing the issue

api components use of audio component

### Example YAML snippet

```yaml
substitutions:
  name: esp32-s3-box-3-059d20
  friendly_name: ESP32 S3 Box 3 059d20
  micro_wake_word_model: hey_jarvis
packages:
  esphome.voice-assistant:
    url: https://github.com/esphome/wake-word-voice-assistants/
    file: esp32-s3-box-3/esp32-s3-box-3.yaml
    ref: main
    refresh: 0d
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: FExkKc18nM0Bpb4jdayzlU5Db4EUO/l9QJsiQUlpUaE=

logger:
  level: INFO

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2024.11.0
INFO Reading configuration /config/esp32-s3-box-3-059d20.yaml...
INFO Cloning https://github.com/esphome/esphome.git@pull/5230/head
INFO Fetching pull/5230/head
INFO Cloning https://github.com/jesserockz/esphome-components.git@None
WARNING GPIO0 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Updating https://github.com/jesserockz/esp32-s3-box-3-board.git@main
INFO Updating https://github.com/espressif/esp-adf@v2.5
INFO Updating submodules (components/esp-sr, components/esp-adf-libs) for https://github.com/espressif/esp-adf@v2.5
INFO Updating https://github.com/espressif/esp-dsp@v1.2.0
INFO Updating https://github.com/espressif/esp-tflite-micro@v1.3.1
INFO Updating https://github.com/espressif/esp-nn@v1.1.0
INFO Compiling app...
Processing esp32-s3-box-3-059d20 (board: esp32s3box; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
Library Manager: Installing esphome/noise-c @ 0.1.6
INFO Installing esphome/noise-c @ 0.1.6
Unpacking  [####################################]  100%
Library Manager: noise-c@0.1.6 has been installed!
INFO noise-c@0.1.6 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing esphome/libsodium @ 1.10018.4
INFO Installing esphome/libsodium @ 1.10018.4
Unpacking  [####################################]  100%
Library Manager: libsodium@1.10018.4 has been installed!
INFO libsodium@1.10018.4 has been installed!
Library Manager: Installing kahrendt/ESPMicroSpeechFeatures @ 1.1.0
INFO Installing kahrendt/ESPMicroSpeechFeatures @ 1.1.0
Unpacking  [####################################]  100%
Library Manager: ESPMicroSpeechFeatures@1.1.0 has been installed!
INFO ESPMicroSpeechFeatures@1.1.0 has been installed!
HARDWARE: ESP32S3 240MHz, 320KB RAM, 16MB Flash
 - framework-espidf @ 3.40408.0 (4.4.8) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5 
 - toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Generating assembly for certificate bundle...
Dependency Graph
|-- noise-c @ 0.1.6
|-- ESPMicroSpeechFeatures @ 1.1.0
Generating assembly for .pioenvs/esp32-s3-box-3-059d20/duer_profile.S
Compiling .pioenvs/esp32-s3-box-3-059d20/src/esphome/components/api/api_connection.o
Compiling .pioenvs/esp32-s3-box-3-059d20/src/esphome/components/api/api_frame_helper.o
Compiling .pioenvs/esp32-s3-box-3-059d20/src/esphome/components/api/api_pb2.o
Compiling .pioenvs/esp32-s3-box-3-059d20/src/esphome/components/api/api_pb2_service.o
In file included from src/esphome/components/voice_assistant/voice_assistant.h:16,
                 from src/esphome/components/api/api_connection.cpp:22:
src/esphome/components/speaker/speaker.h:13:10: fatal error: esphome/components/audio/audio.h: No such file or directory
 #include "esphome/components/audio/audio.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/esp32-s3-box-3-059d20/src/esphome/components/api/api_connection.o] Error 1
========================= [FAILED] Took 19.43 seconds =========================
```
```


### Additional information

I can see that `/esphome/esphome/components/audio/audio.h` exists within the container image.

Container image is sha256:dd54af9b703c7c21ab9a4cc3c8458683b1438856a539f189247841ed670e4266 from image tag `ghcr.io/esphome/esphome:2024.11`.

**Comment by ijc** [comment]
I somehow missed https://github.com/esphome/esphome/pull/7794 which is certain to be the issue here.
