### ISSUE TITLE
Link error in ethernet component

### ISSUE THREAD

**Issue by StefanTT** [esphome/issues#4188]
### The problem

When compiling the project then there is a link error in the ethernet component (see included log).
It worked with esphome 2022.12.8.

### Which version of ESPHome has the issue?

2023.2.1

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

-

### What platform are you using?

ESP32

### Board

wemos_d1_mini32

### Component causing the issue

ethernet

### Example YAML snippet

```yaml
substitutions:
  devicename: racky
  network: !secret network
  fqdn: ${devicename}.${network}

esphome:
  name: ${devicename}

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password
  reboot_timeout: 60min

ota:
  password: !secret ota_password

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  power_pin: GPIO5
  phy_addr: 1
```

### Anything in the logs that might be useful for us?

```txt
[...]
Archiving .pioenvs/racky/libFrameworkArduino.a
Indexing .pioenvs/racky/libFrameworkArduino.a
Linking .pioenvs/racky/firmware.elf
/home/stefan/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/racky/src/esphome/components/ethernet/ethernet_component.cpp.o:(.literal._ZN7esphome8ethernet17EthernetComponent5setupEv+0x44): undefined reference to `esp_eth_phy_new_jl1101'
/home/stefan/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/racky/src/esphome/components/ethernet/ethernet_component.cpp.o: in function `esphome::ethernet::EthernetComponent::setup()':
/home/stefan/Projekte/Computer/SmartRackPowerSwitch/firmware/.esphome/build/racky/src/esphome/components/ethernet/ethernet_component.cpp:57: undefined reference to `esp_eth_phy_new_jl1101'
collect2: error: ld returned 1 exit status
```

**Comment by StefanTT** [comment]
Duplicate of 4174.
