### ISSUE TITLE
ESPHome 2022.11.1 not building due to ble_client

### ISSUE THREAD

**Issue by benpage** [esphome/issues#3825]
### The problem

Building for the ESP32 crashes, error log attached

### Which version of ESPHome has the issue?

2022.11.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.11.4

### What platform are you using?

ESP32

### Board

generic

### Component causing the issue

ble_client

### Example YAML snippet

```yaml
substitutions:
  name: esp32-bluetooth-proxy
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

light:
  - platform: status_led
    name: "Switch state"
    pin: GPIO2

external_components:
  - source: github://WeekendWarrior1/esphome@powerpal_ble
    # requires ble_client because I had to add some small features to authenticate properly
    components: [ ble_client, powerpal_ble ]

# optional requirement used with daily energy sensor
time:
  - platform: homeassistant
    id: homeassistant_time

ble_client:
  - mac_address: REDACTED
    id: powerpal

sensor:
  - platform: powerpal_ble
    ble_client_id: powerpal
    power:
      name: "Powerpal Power"
    daily_energy:
      name: "Powerpal Daily Energy"
    energy:
      name: "Powerpal Total Energy"
    battery_level:
      name: "Powerpal Battery"
    pairing_code: REDACTED
    notification_interval: 1 # get updates every 1 minute
    pulses_per_kwh: 3200
    time_id: homeassistant_time # daily energy still works without a time_id, but recommended to include one to properly handle daylight savings, etc.
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/esp32-bluetooth-proxy-bb7eb0.yaml...
WARNING GPIO2 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Detected timezone 'Australia/Sydney'
INFO Generating C++ source...
INFO Compiling app...
Processing esp32-bluetooth-proxy-bb7eb0 (board: esp32dev; framework: arduino; platform: platformio/espressif32 @ 3.5.0)
--------------------------------------------------------------------------------
Library Manager: Installing esphome/AsyncTCP-esphome @ 1.2.2
INFO Installing esphome/AsyncTCP-esphome @ 1.2.2
Unpacking  [####################################]  100%
Library Manager: AsyncTCP-esphome@1.2.2 has been installed!
INFO AsyncTCP-esphome@1.2.2 has been installed!
Library Manager: Installing esphome/ESPAsyncWebServer-esphome @ 2.1.0
INFO Installing esphome/ESPAsyncWebServer-esphome @ 2.1.0
Unpacking  [####################################]  100%
Library Manager: ESPAsyncWebServer-esphome@2.1.0 has been installed!
INFO ESPAsyncWebServer-esphome@2.1.0 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing esphome/Improv @ 1.2.3
INFO Installing esphome/Improv @ 1.2.3
Unpacking  [####################################]  100%
Library Manager: Improv@1.2.3 has been installed!
INFO Improv@1.2.3 has been installed!
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 1.0
|-- FS @ 1.0
|-- Update @ 1.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- AsyncTCP-esphome @ 1.2.2
|-- DNSServer @ 1.1.0
|-- ESPmDNS @ 1.0
|-- Improv @ 1.2.3
Compiling /data/esp32-bluetooth-proxy-bb7eb0/.pioenvs/esp32-bluetooth-proxy-bb7eb0/src/esphome/components/api/api_connection.cpp.o
Compiling /data/esp32-bluetooth-proxy-bb7eb0/.pioenvs/esp32-bluetooth-proxy-bb7eb0/src/esphome/components/api/api_frame_helper.cpp.o
Compiling /data/esp32-bluetooth-proxy-bb7eb0/.pioenvs/esp32-bluetooth-proxy-bb7eb0/src/esphome/components/api/api_pb2.cpp.o
Compiling /data/esp32-bluetooth-proxy-bb7eb0/.pioenvs/esp32-bluetooth-proxy-bb7eb0/src/esphome/components/api/api_pb2_service.cpp.o
Compiling /data/esp32-bluetooth-proxy-bb7eb0/.pioenvs/esp32-bluetooth-proxy-bb7eb0/src/esphome/components/api/api_server.cpp.o
Compiling /data/esp32-bluetooth-proxy-bb7eb0/.pioenvs/esp32-bluetooth-proxy-bb7eb0/src/esphome/components/api/list_entities.cpp.o
Compiling /data/esp32-bluetooth-proxy-bb7eb0/.pioenvs/esp32-bluetooth-proxy-bb7eb0/src/esphome/components/api/proto.cpp.o
Compiling /data/esp32-bluetooth-proxy-bb7eb0/.pioenvs/esp32-bluetooth-proxy-bb7eb0/src/esphome/components/api/subscribe_state.cpp.o
Compiling /data/esp32-bluetooth-proxy-bb7eb0/.pioenvs/esp32-bluetooth-proxy-bb7eb0/src/esphome/components/api/user_services.cpp.o
Compiling /data/esp32-bluetooth-proxy-bb7eb0/.pioenvs/esp32-bluetooth-proxy-bb7eb0/src/esphome/components/ble_client/ble_client.cpp.o
Compiling /data/esp32-bluetooth-proxy-bb7eb0/.pioenvs/esp32-bluetooth-proxy-bb7eb0/src/esphome/components/bluetooth_proxy/bluetooth_connection.cpp.o
In file included from src/esphome/components/ble_client/ble_client.cpp:5:0:
src/esphome/components/ble_client/ble_client.h:89:8: error: conflicting return type specified for 'virtual void esphome::ble_client::BLEClient::gattc_event_handler(esp_gattc_cb_event_t, esp_gatt_if_t, esp_ble_gattc_cb_param_t*)'
   void gattc_event_handler(esp_gattc_cb_event_t event, esp_gatt_if_t gattc_if,
        ^
In file included from src/esphome/components/ble_client/ble_client.cpp:4:0:
src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.h:162:16: error:   overriding 'virtual bool esphome::esp32_ble_tracker::ESPBTClient::gattc_event_handler(esp_gattc_cb_event_t, esp_gatt_if_t, esp_ble_gattc_cb_param_t*)'
   virtual bool gattc_event_handler(esp_gattc_cb_event_t event, esp_gatt_if_t gattc_if,
                ^
*** [/data/esp32-bluetooth-proxy-bb7eb0/.pioenvs/esp32-bluetooth-proxy-bb7eb0/src/esphome/components/ble_client/ble_client.cpp.o] Error 1
========================== [FAILED] Took 9.95 seconds ==========================
```

**Comment by pauly2805** [comment]
in your example yaml snippet you are using the powerpal_ble external with the external older modified ble_client?
If so check my post here:
https://community.home-assistant.io/t/powerpal-smart-energy-monitor/263713/238?u=paul09

not sure if this is the cause, it just looks similar

**Comment by adam-olson** [comment]
I am running into a similar issue, worked in 2022.10.2 but stopped working on the 2022.11.x releases, using a switchbot plug, here is the build YAML and the error log I get.

```yaml
substitutions:
  display_name: switchbot-1-esp

esphome:
  name: ${display_name}
  platformio_options:
    board_build.mcu: esp32c3
    board_build.variant: esp32c3  

esp32:
  variant: ESP32C3
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"    

#mqtt:
#  broker: 192.168.0.253
#  username: !secret Mqtt_User
#  password: !secret Mqtt_Pass

# Enable logging
logger:

api:
  encryption:
    key: !secret ESPHome_key

ota:
  password: !secret OTA_Pass
  
button:
  - platform: safe_mode
    name: ${display_name} (Safe Mode)

# Change the WiFi config to a non-static IP if needed
wifi:
  ssid: !secret WiFi_SSID
  password: !secret WiFi_Pass
  manual_ip:
    static_ip: 192.168.0.109
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 192.168.0.253

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO20
      inverted: true
    cf_pin: GPIO18
    cf1_pin: GPIO19
    model: BL0937
    current_resistor: 0.0011
    voltage_divider: 1450
    current:
      name: ${display_name} Amps
    voltage:
      name: ${display_name} Volts
    power:
      name: ${display_name} Watts
      accuracy_decimals: 0       
    energy:
      name: ${display_name} Energy
    update_interval: 3s
    change_mode_every: 4

switch:
  - platform: gpio
    name: ${display_name} Relay
    id: relay
    device_class: outlet
    pin: GPIO6
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      then:
        - light.turn_on: white_led
    on_turn_off:
      then:
        - light.turn_off: white_led  

binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: GPIO2
      mode: INPUT_PULLUP
      inverted: true
    name: ${display_name} Button
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - switch.toggle: relay 

light:
  - platform: binary
    internal: true
    name: ${display_name} White LED
    id: white_led
    output: white_output    

output:
  - id: white_output
    platform: gpio
    pin: GPIO7
    inverted: true

status_led:
  pin:
    number: GPIO8
    inverted: true

```

```
INFO Reading configuration /config/switchbot-1.yaml...
WARNING GPIO2 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO8 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing switchbot-1-esp (board: esp32dev; framework: espidf; platform: platformio/espressif32 @ 3.5.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32C3 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40302.0 (4.3.2) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch2 
 - toolchain-xtensa-esp32s2 @ 8.4.0+2021r2-patch2
Installing ESP-IDF's Python dependencies
Collecting future>=0.15.2
  Downloading future-0.18.2.tar.gz (829 kB)
Collecting pyparsing<2.4.0,>=2.0.3
  Downloading pyparsing-2.3.1-py2.py3-none-any.whl (61 kB)
Building wheels for collected packages: future
  Building wheel for future (setup.py): started
  Building wheel for future (setup.py): finished with status 'done'
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=24ac6fc54be179e610776de9911b955d4516e1e51a0b103117c3bf851bb92c16
  Stored in directory: /root/.cache/pip/wheels/2f/a0/d3/4030d9f80e6b3be787f19fc911b8e7aa462986a40ab1e4bb94
Successfully built future
Installing collected packages: pyparsing, future
  Attempting uninstall: pyparsing
    Found existing installation: pyparsing 3.0.9
    Uninstalling pyparsing-3.0.9:
      Successfully uninstalled pyparsing-3.0.9
Successfully installed future-0.18.2 pyparsing-2.3.1
Reading CMake configuration...
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
Compiling .pioenvs/switchbot-1-esp/src/esphome/components/api/api_connection.o
Compiling .pioenvs/switchbot-1-esp/src/esphome/components/api/api_server.o
Compiling .pioenvs/switchbot-1-esp/src/esphome/components/esp32_ble_client/ble_client_base.o
Compiling .pioenvs/switchbot-1-esp/src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.o
src/esphome/components/esp32_ble_client/ble_client_base.cpp: In member function 'float esphome::esp32_ble_client::BLEClientBase::parse_char_value(uint8_t*, uint16_t)':
src/esphome/components/esp32_ble_client/ble_client_base.cpp:234:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 2) {
       ^~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:237:5: note: here
     case 0x7:  // uint24.
     ^~~~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:238:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 3) {
       ^~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:241:5: note: here
     case 0x8:  // uint32.
     ^~~~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:242:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 4) {
       ^~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:245:5: note: here
     case 0xC:  // int8.
     ^~~~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:249:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 2) {
       ^~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:252:5: note: here
     case 0xF:  // int24.
     ^~~~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:253:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 3) {
       ^~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:256:5: note: here
     case 0x10:  // int32.
     ^~~~
In file included from src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp:13:
src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp: In static member function 'static bool esphome::esp32_ble_tracker::ESP32BLETracker::ble_setup()':
/config/.esphome/platformio/packages/framework-espidf/components/bt/include/esp32c3/include/esp_bt.h:182:1: warning: missing initializer for member 'esp_bt_controller_config_t::coex_param_en' [-Wmissing-field-initializers]
 };
 ^
src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp:196:40: note: in expansion of macro 'BT_CONTROLLER_INIT_CONFIG_DEFAULT'
       esp_bt_controller_config_t cfg = BT_CONTROLLER_INIT_CONFIG_DEFAULT();
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/config/.esphome/platformio/packages/framework-espidf/components/bt/include/esp32c3/include/esp_bt.h:182:1: warning: missing initializer for member 'esp_bt_controller_config_t::coex_use_hooks' [-Wmissing-field-initializers]
 };
 ^
src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp:196:40: note: in expansion of macro 'BT_CONTROLLER_INIT_CONFIG_DEFAULT'
       esp_bt_controller_config_t cfg = BT_CONTROLLER_INIT_CONFIG_DEFAULT();
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Compiling .pioenvs/switchbot-1-esp/src/esphome/components/mdns/mdns_component.o
Compiling .pioenvs/switchbot-1-esp/src/esphome/core/application.o
Compiling .pioenvs/switchbot-1-esp/src/esphome/core/util.o
Compiling .pioenvs/switchbot-1-esp/src/main.o
Linking .pioenvs/switchbot-1-esp/firmware.elf
/config/.esphome/platformio/packages/toolchain-riscv32-esp/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/bin/ld: .pioenvs/switchbot-1-esp/src/main.o: in function `esphome::bluetooth_proxy::BluetoothConnection::BluetoothConnection()':
/config/.esphome/build/switchbot-1-esp/src/esphome/components/bluetooth_proxy/bluetooth_connection.h:12: undefined reference to `vtable for esphome::bluetooth_proxy::BluetoothConnection'
/config/.esphome/platformio/packages/toolchain-riscv32-esp/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/bin/ld: /config/.esphome/build/switchbot-1-esp/src/esphome/components/bluetooth_proxy/bluetooth_connection.h:12: undefined reference to `vtable for esphome::bluetooth_proxy::BluetoothConnection'
/config/.esphome/platformio/packages/toolchain-riscv32-esp/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/bin/ld: /config/.esphome/build/switchbot-1-esp/src/esphome/components/bluetooth_proxy/bluetooth_connection.h:12: undefined reference to `vtable for esphome::bluetooth_proxy::BluetoothConnection'
/config/.esphome/platformio/packages/toolchain-riscv32-esp/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/bin/ld: /config/.esphome/build/switchbot-1-esp/src/esphome/components/bluetooth_proxy/bluetooth_connection.h:12: undefined reference to `vtable for esphome::bluetooth_proxy::BluetoothConnection'
/config/.esphome/platformio/packages/toolchain-riscv32-esp/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/bin/ld: .pioenvs/switchbot-1-esp/src/esphome/components/bluetooth_proxy/bluetooth_proxy.o: in function `esphome::bluetooth_proxy::BluetoothProxy::bluetooth_gatt_read(esphome::api::BluetoothGATTReadRequest const&)':
/config/.esphome/build/switchbot-1-esp/src/esphome/components/bluetooth_proxy/bluetooth_proxy.cpp:164: undefined reference to `esphome::bluetooth_proxy::BluetoothConnection::read_characteristic(unsigned short)'
/config/.esphome/platformio/packages/toolchain-riscv32-esp/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/bin/ld: .pioenvs/switchbot-1-esp/src/esphome/components/bluetooth_proxy/bluetooth_proxy.o: in function `esphome::bluetooth_proxy::BluetoothProxy::bluetooth_gatt_write(esphome::api::BluetoothGATTWriteRequest const&)':
/config/.esphome/build/switchbot-1-esp/src/esphome/components/bluetooth_proxy/bluetooth_proxy.cpp:176: undefined reference to `esphome::bluetooth_proxy::BluetoothConnection::write_characteristic(unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
/config/.esphome/platformio/packages/toolchain-riscv32-esp/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/bin/ld: .pioenvs/switchbot-1-esp/src/esphome/components/bluetooth_proxy/bluetooth_proxy.o: in function `esphome::bluetooth_proxy::BluetoothProxy::bluetooth_gatt_read_descriptor(esphome::api::BluetoothGATTReadDescriptorRequest const&)':
/config/.esphome/build/switchbot-1-esp/src/esphome/components/bluetooth_proxy/bluetooth_proxy.cpp:192: undefined reference to `esphome::bluetooth_proxy::BluetoothConnection::read_descriptor(unsigned short)'
/config/.esphome/platformio/packages/toolchain-riscv32-esp/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/bin/ld: .pioenvs/switchbot-1-esp/src/esphome/components/bluetooth_proxy/bluetooth_proxy.o: in function `esphome::bluetooth_proxy::BluetoothProxy::bluetooth_gatt_write_descriptor(esphome::api::BluetoothGATTWriteDescriptorRequest const&)':
/config/.esphome/build/switchbot-1-esp/src/esphome/components/bluetooth_proxy/bluetooth_proxy.cpp:206: undefined reference to `esphome::bluetooth_proxy::BluetoothConnection::write_descriptor(unsigned short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/config/.esphome/platformio/packages/toolchain-riscv32-esp/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/bin/ld: .pioenvs/switchbot-1-esp/src/esphome/components/bluetooth_proxy/bluetooth_proxy.o: in function `esphome::bluetooth_proxy::BluetoothProxy::bluetooth_gatt_notify(esphome::api::BluetoothGATTNotifyRequest const&)':
/config/.esphome/build/switchbot-1-esp/src/esphome/components/bluetooth_proxy/bluetooth_proxy.cpp:236: undefined reference to `esphome::bluetooth_proxy::BluetoothConnection::notify_characteristic(unsigned short, bool)'
collect2: error: ld returned 1 exit status
*** [.pioenvs/switchbot-1-esp/firmware.elf] Error 1
========================= [FAILED] Took 304.19 seconds =========================
```

**Comment by benpage** [comment]
> in your example yaml snippet you are using the powerpal_ble external with the external older modified ble_client? If so check my post here: https://community.home-assistant.io/t/powerpal-smart-energy-monitor/263713/238?u=paul09
> 
> not sure if this is the cause, it just looks similar

I mean yes, it certainly looks very similar!

**Comment by mschlereth** [comment]
I have the same issue when adding  bluetooth_proxy active: true causes compile error "esp32_ble_client/ble_client_base.cpp:234:7: warning: this statement may fall through"

`substitutions:
  device_name: esp-test-devboard
  friendly_name: esp test devboard

esphome:
  name: ${device_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .pickle.net
  manual_ip:
    static_ip: 10.10.3.14
    gateway: 10.10.3.1
    subnet: 255.255.255.0

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${friendly_name} AP
    password: !secret ap_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

# Text sensors with general information.
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${device_name} IP

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: ${device_name} Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${device_name} WiFi Signal
    update_interval: 60s

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
`


`INFO Reading configuration /config/esphome/esp-test-devboard.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esp-test-devboard (board: esp32dev; framework: espidf; platform: platformio/espressif32 @ 3.5.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40302.0 (4.3.2) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch2 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch2 
 - toolchain-xtensa-esp32s2 @ 8.4.0+2021r2-patch2
Reading CMake configuration...
Generating assembly for certificate bundle...
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
No dependencies
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/api/api_connection.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/api/api_frame_helper.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/api/api_pb2.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/api/api_pb2_service.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/api/api_server.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/api/list_entities.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/api/proto.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/api/subscribe_state.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/api/user_services.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/bluetooth_proxy/bluetooth_connection.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/bluetooth_proxy/bluetooth_proxy.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/esp32/core.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/esp32/gpio_arduino.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/esp32/gpio_idf.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/esp32/preferences.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/esp32_ble_client/ble_characteristic.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/esp32_ble_client/ble_client_base.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/esp32_ble_client/ble_service.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/logger/logger.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/md5/md5.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/mdns/mdns_component.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/mdns/mdns_esp32_arduino.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/mdns/mdns_esp8266.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/mdns/mdns_esp_idf.o
src/esphome/components/esp32_ble_client/ble_client_base.cpp: In member function 'float esphome::esp32_ble_client::BLEClientBase::parse_char_value(uint8_t*, uint16_t)':
src/esphome/components/esp32_ble_client/ble_client_base.cpp:234:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 2) {
       ^~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:237:5: note: here
     case 0x7:  // uint24.
     ^~~~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:238:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 3) {
       ^~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:241:5: note: here
     case 0x8:  // uint32.
     ^~~~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:242:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 4) {
       ^~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:245:5: note: here
     case 0xC:  // int8.
     ^~~~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:249:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 2) {
       ^~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:252:5: note: here
     case 0xF:  // int24.
     ^~~~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:253:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 3) {
       ^~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:256:5: note: here
     case 0x10:  // int32.
     ^~~~
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/mdns/mdns_rp2040.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/network/util.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/ota/ota_backend_arduino_esp32.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/ota/ota_backend_arduino_esp8266.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/ota/ota_backend_arduino_rp2040.o
Compiling /data/esp-test-devboard/.pioenvs/esp-test-devboard/src/esphome/components/ota/ota_backend_esp_idf.o`

**Comment by adam-olson** [comment]
Was able to get the build to complete by doing a "clean build files" and then doing the build again.

**Comment by ssieb** [comment]
Yes, the IDF build system doesn't always rebuild things when necessary, so a clean build is required sometimes.  The `vtable` error is a good indication of this.
@mschlereth the warning is not a compile error.

**Comment by jabbas** [comment]
I confirm - `clean build files` does the job
