### ISSUE TITLE
component BLE RSSI not working on esphome 1.13.3

### ISSUE THREAD

**Issue by animavitis** [esphome/issues#418]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

PIP
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32
**Affected component:**

BLE_RSSI

**Description of problem:**
ccompilation error

**Problem-relevant YAML-configuration entries:**
```
  - platform: ble_rssi
    mac_address: 84:A4:66:89:75:8E
    name: "Sygonix"
    id: rssi_sygonix
    on_value:
    - mqtt.publish_json:
        topic: home_presence/room_1
        payload: |-
          root["id"] = "84:A4:66:89:75:8E";
          root["name"] = "sygonix";
          root["distance"] = (0.89)* pow(id(rssi_sygonix).value/-59,7.7095) + 0.11;
```

**Traceback (if applicable):**

```
Archiving .pioenvs\przedpokoj\libb60\libAsyncMqttClient_ID346.a
Indexing .pioenvs\przedpokoj\libb60\libAsyncMqttClient_ID346.a
src\main.cpp: In lambda function:
src\main.cpp:932:52: error: 'class esphome::ble_rssi::BLERSSISensor' has no member named 'value'
root["distance"] = (0.89)* pow(rssi_sygonix->value/-59,7.7095) + 0.11;
^
Compiling .pioenvs\przedpokoj\lib244\WiFi\WiFiSTA.cpp.o
Compiling .pioenvs\przedpokoj\lib244\WiFi\WiFiScan.cpp.o
```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
There's no such property `value` on sensors, it's called `state`.

(side note: value did exist some time ago, but was deprecated ages ago)
