### ISSUE TITLE
lvgl_esphome.h:57:44: error: cannot convert 'lv_img_dsc_t*' to 'esphome::image::Image*'

### ISSUE THREAD

**Issue by derMicro** [esphome/issues#6457]
### The problem

Compiling .pioenvs/p-sz-ble-sensecapnightlight/src/esphome/components/lvgl/lvgl_esphome.cpp.o
In file included from src/esphome/components/lvgl/font.cpp:1:
src/esphome/components/lvgl/lvgl_esphome.h: In function 'void esphome::lvgl::lv_img_set_src(lv_obj_t*, esphome::image::Image*)':
src/esphome/components/lvgl/lvgl_esphome.h:57:44: error: cannot convert 'lv_img_dsc_t*' to 'esphome::image::Image*'
   57 |   lv_img_set_src(obj, image->get_lv_img_dsc());
      |                       ~~~~~~~~~~~~~~~~~~~~~^~
      |                                            |
      |                                            lv_img_dsc_t*
src/esphome/components/lvgl/lvgl_esphome.h:56:66: note:   initializing argument 2 of 'void esphome::lvgl::lv_img_set_src(lv_obj_t*, esphome::image::Image*)'
   56 | inline void lv_img_set_src(lv_obj_t *obj, esphome::image::Image *image) {
      |                                           ~~~~~~~~~~~~~~~~~~~~~~~^~~~~
In file included from src/esphome/components/lvgl/lvgl_esphome.cpp:6:
src/esphome/components/lvgl/lvgl_esphome.h: In function 'void esphome::lvgl::lv_img_set_src(lv_obj_t*, esphome::image::Image*)':
src/esphome/components/lvgl/lvgl_esphome.h:57:44: error: cannot convert 'lv_img_dsc_t*' to 'esphome::image::Image*'
   57 |   lv_img_set_src(obj, image->get_lv_img_dsc());
      |                       ~~~~~~~~~~~~~~~~~~~~~^~
      |                                            |
      |                                            lv_img_dsc_t*
src/esphome/components/lvgl/lvgl_esphome.h:56:66: note:   initializing argument 2 of 'void esphome::lvgl::lv_img_set_src(lv_obj_t*, esphome::image::Image*)'
   56 | inline void lv_img_set_src(lv_obj_t *obj, esphome::image::Image *image) {
      |                                           ~~~~~~~~~~~~~~~~~~~~~~~^~~~~
*** [.pioenvs/p-sz-ble-sensecapnightlight/src/esphome/components/lvgl/font.cpp.o] Error 1
*** [.pioenvs/p-sz-ble-sensecapnightlight/src/esphome/components/lvgl/lvgl_esphome.cpp.o] Error 1
========================= [FAILED] Took 94.59 seconds =========================

```
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0
    
   and
framework:
    type: esp-idf
    version: 5.2.2
    platform_version: 6.7.0
    #(working on 2024.10.x)
```

### Which version of ESPHome has the issue?

2024.11.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.11.2

### What platform are you using?

ESP32-IDF

### Board

esp32-s3-devkitc-1 (Sensecap Indicator)

### Component causing the issue

lvgl image ?

### Example YAML snippet

```yaml
...
image:
  - file: 'lvgl/sensecap_wp1.png'
    id: wallpaper
    resize: 480x480
    type: RGB565
    use_transparency: true

...

lvgl:
  displays:
    - sensecap_display
  touchscreens:
    - sensecap_touchscreen
  disp_bg_image: wallpaper
```

### Additional information

I do not use any images except the wallpaper image
Until the last release of 2024.10. the code worked without problems
