### ISSUE TITLE
GitHub Issue: ESPHome 2025.7.0 – ESP32-S3 Fails to Build with web_server_base (Missing IPv6Address.h in Arduino core 3.1.3)

### ISSUE THREAD

**Issue by jlipsit** [esphome/issues#7237]
# Description

After upgrading to **ESPHome 2025.7.0**, any ESP32-S3 build using the official `web_server_base` component fails with this error:

```
.piolibdeps/esp32-s3-devkitc-1/AsyncTCP-esphome/src/AsyncTCP.h:26:10: fatal error: IPv6Address.h: No such file or directory
 #include "IPv6Address.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
```

---

## Details

* The [[2025.7.0 changelog](https://esphome.io/changelog/2025.7.0.html)](https://esphome.io/changelog/2025.7.0.html) shows ESPHome now pins ESP32 Arduino core to 3.1.3.
* The file `IPv6Address.h` was added in Arduino-ESP32 **3.1.6** and is not present in 3.1.3.
* The `AsyncTCP-esphome` library (used by `web_server_base`) requires this header and thus Arduino core 3.1.6 or newer for ESP32-S3 and ESP32-C3 boards.

---

## Impact

* All ESPHome projects using ESP32-S3 and the official `web_server_base` component cannot build on ESPHome 2025.7.0.
* This breaks built-in web server functionality for ESP32-S3 and likely ESP32-C3.
* Pinning `platformio_options` or the Arduino core in YAML does not resolve the issue, since ESPHome’s build system enforces 3.1.3.

---

## Steps to reproduce

1. Update ESPHome to 2025.7.0 (Home Assistant OS add-on or standalone)
2. Use an ESP32-S3 board (e.g. esp32-s3-devkitc-1)
3. Add `web_server_base:` to YAML
4. Attempt to build—observe fatal missing `IPv6Address.h` error.

---

## Relevant YAML snippet

```yaml
esphome:
  name: test-s3r
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: 3.1.3
web_server_base:
```

---

## What is the expected behavior?

* ESPHome should use Arduino-ESP32 3.1.6+ or update `AsyncTCP-esphome` to not require IPv6Address.h.
* Or, provide guidance for ESP32-S3 users relying on web server features.

---

## Environment

* ESPHome version: 2025.7.0
* Platform: Home Assistant OS add-on (but likely affects all builds)
* Board: ESP32-S3 (esp32-s3-devkitc-1)

---

## Additional information

* This worked fine with ESPHome 2025.6.x (which used Arduino core 3.1.6 by default).
* No mention of the compatibility break in the [[2025.7.0 changelog](https://esphome.io/changelog/2025.7.0.html)](https://esphome.io/changelog/2025.7.0.html).
* Workarounds (pinning platform, pinning framework, clearing PlatformIO cache) do **not** resolve this on Home Assistant OS.
* [[PlatformIO issue 1155](https://github.com/platformio/platform-espressif32/issues/1155)](https://github.com/platformio/platform-espressif32/issues/1155) confirms that the asset for 3.1.6 was also recently removed by Espressif, compounding the problem.

---

Thank you for reviewing!

**Comment by jlipsit** [comment]
After rebuild with ESPHome 2025.7.1 and some config changes all is well. Closed.

**Comment by brainhig** [comment]
> After rebuild with ESPHome 2025.7.1 and some config changes all is well. Closed.

Could you share the config changes you made? I'm having the same problem with 2025.7.1

**Comment by jlipsit** [comment]
Hi Brian,

Not sure this will work for you but it took me awhile to stumble on this for my instance.  

I had a custom component (in component.py) that was adding the following library's:

    #Do not add, just use web_server_base:  in YAML to load these automatically.
    # Let ESPHome select compatible versions instead of pinning old versions
    #cg.add_library("esphome/AsyncTCP-esphome", None)              # AsyncTCP - ESPHome-managed
    #cg.add_library("esphome/ESPAsyncWebServer-esphome", None)     # ESPAsyncWebServer - ESPHome-managed

Just remove them or # REM them out.

Then in your YAML add this after your Wi-Fi settings:

# 👇 ADD THIS HERE (after Wi-Fi settings) in place of adding library's manually in component.py for custom component. After ESP home 2025.7.x update
#  Previously AsyncTCP and ESPAsyncWebServer were added in component.py

web_server_base:


Also do not specify and version here:

esp32:
  board: esp32-s3-devkitc-1   # stay with the known board ID
  framework:
    type: arduino
    # Do not specify Version


Hopefully making these changes will get you up and running.

**Comment by brainhig** [comment]
Thank you for the update! I appreciate your time!

Sadly, I guess my problem is different. I thought perhaps the S3 and C3 were similar enough that it was the same problem. Compile goes OK, exept for the errors about RMT and ADC libraries having issues, and the bin is uploaded, but the device still reports that it's on ESPHome version 2025.6.3
Bummer :/
