### ISSUE TITLE
Dashboard fails to start using Python 3

### ISSUE THREAD

**Issue by tomason** [esphome/issues#368]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Fedora 29 armv7 (Banana Pi)
Python 3.7

**ESP (ESP32/ESP8266, Board/Sonoff):**

Not applicable

**Affected component:**

ESPHome dashboard

**Description of problem:**
The dashboard fails to start in 1.13 running on Python 3. It used to work with 1.12. The issue is easy to fix, there is a missing method in Python 3 (see bellow).

**Problem-relevant YAML-configuration entries:**
Not applicable

**Traceback (if applicable):**

```
Traceback (most recent call last):
  File "/home/esphome/.local/bin/esphome", line 11, in <module>
    sys.exit(main())
  File "/home/esphome/.local/lib/python3.7/site-packages/esphome/__main__.py", line 483, in main
    return run_esphome(sys.argv)
  File "/home/esphome/.local/lib/python3.7/site-packages/esphome/__main__.py", line 459, in run_esphome
    return PRE_CONFIG_ACTIONS[args.command](args)
  File "/home/esphome/.local/lib/python3.7/site-packages/esphome/__main__.py", line 348, in command_dashboard
    from esphome.dashboard import dashboard
  File "/home/esphome/.local/lib/python3.7/site-packages/esphome/dashboard/dashboard.py", line 189, in <module>
    class EsphomeCommandWebSocket(tornado.websocket.WebSocketHandler):
  File "/home/esphome/.local/lib/python3.7/site-packages/esphome/dashboard/dashboard.py", line 172, in websocket_class
    for _, method in cls.__dict__.iteritems():
AttributeError: 'mappingproxy' object has no attribute 'iteritems'
```

**Additional information and things you've tried:**
Replace line `172` in file `esphome/dashboard/dashboard.py` to say `for _, method in cls.__dict__.items():`
