### ISSUE TITLE
LibreTiny compilation Errors in v.2023.11.6

### ISSUE THREAD

**Issue by elproko** [esphome/issues#5176]
### The problem

After upgrade to 2023.11.6 LibreTiny devices cannot be updated. Compilation fails all the time.

### Which version of ESPHome has the issue?

2023.11.6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.11.3

### What platform are you using?

BK72XX

### Board

wb2s, cb2s

### Component causing the issue

all

### Example YAML snippet

```yaml
substitutions:
  name: techiumbk
#  voltage_divider: "2"
#  current_resistor: "0.001"
#  current_multiply: "1000.0"

esphome:
  name: ${name}
  friendly_name: "Techium BK"

bk72xx:
  board: cb2s
  #generic-bk7231n-qfn32-tuya

logger:
  id: component_logger
  level: DEBUG
  baud_rate: 0 #disable logging over uart

web_server: 
  port: 80   
  local: true
  

switch:
  - platform: gpio
    name: Relay
    id: techiumbk_relay
    pin: P26
    on_turn_on:
      - switch.turn_on: techiumbk_led
    on_turn_off:
      - switch.turn_off: techiumbk_led
  - platform: gpio
    name: Led
    id: techiumbk_led
    pin: P8
    inverted: True

binary_sensor:
  - platform: gpio
    name: "Button"
    pin:
#      inverted: false
# Tx1
      number: P11
      mode:
        input: True
        pulldown: True
    on_press:
      - switch.toggle: techiumbk_relay

sensor:
  - platform: hlw8012
    model: BL0937
    current_resistor: 0.001
    voltage_divider: 794.5

    sel_pin:
      number: P24
      inverted: true
    cf_pin:
      number: P7
      inverted: true
    cf1_pin:
      number: P6
      inverted: true
#    initial_mode: VOLTAGE
    change_mode_every: 2
    voltage:
      accuracy_decimals: 3
      name: "Voltage"
    current:
      name: "Current"
      accuracy_decimals: 3
      filters:
        - multiply: 0.4244
    power:
      name: "Power"
      accuracy_decimals: 3
    energy:
      name: "Energy"
      accuracy_decimals: 3
    update_interval: 10s

api:
  encryption:
    key: "xxxxxx anonymized xxxxxx"
    
ota:
   password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 1.2.3.4
    gateway: 1.2.3.1
    subnet: 255.255.255.0
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2023.11.6
INFO Reading configuration /config/esphome/ip67_techiumbk.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing techiumbk (board: cb2s; framework: arduino; platform: libretiny @ 1.4.1)
--------------------------------------------------------------------------------
Error processing line 1 of /root/.platformio/penv/.libretiny/lib/python3.11/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "<frozen site>", line 192, in addpackage
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
Error processing line 1 of /root/.platformio/penv/.libretiny/lib/python3.11/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "<frozen site>", line 192, in addpackage
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
LibreTiny: Installing Python dependencies
Error processing line 1 of /root/.platformio/penv/.libretiny/lib/python3.11/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "<frozen site>", line 192, in addpackage
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
Error processing line 1 of /root/.platformio/penv/.libretiny/lib/python3.11/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "<frozen site>", line 192, in addpackage
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
Collecting ltchiptool<5.0,>=4.5.1
  Downloading ltchiptool-4.8.0-py3-none-any.whl.metadata (3.9 kB)
Collecting bitstruct<9.0.0,>=8.1.1 (from ltchiptool<5.0,>=4.5.1)
  Downloading bitstruct-8.1.1-py2.py3-none-any.whl (8.1 kB)
Collecting bk7231tools<2.0.0,>=1.5.1 (from ltchiptool<5.0,>=4.5.1)
  Downloading bk7231tools-1.5.1-py3-none-any.whl.metadata (790 bytes)
Collecting click<9.0.0,>=8.1.3 (from ltchiptool<5.0,>=4.5.1)
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting colorama<0.5.0,>=0.4.5 (from ltchiptool<5.0,>=4.5.1)
  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting hexdump<4.0,>=3.3 (from ltchiptool<5.0,>=4.5.1)
  Downloading hexdump-3.3.zip (12 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Error processing line 1 of /root/.platformio/penv/.libretiny/lib/python3.11/site-packages/distutils-precedence.pth:
      
        Traceback (most recent call last):
          File "<frozen site>", line 192, in addpackage
          File "<string>", line 1, in <module>
        ModuleNotFoundError: No module named '_distutils_hack'
      
      Remainder of file ignored
      Error processing line 1 of /root/.platformio/penv/.libretiny/lib/python3.11/site-packages/distutils-precedence.pth:
      
        Traceback (most recent call last):
          File "<frozen site>", line 192, in addpackage
          File "<string>", line 1, in <module>
        ModuleNotFoundError: No module named '_distutils_hack'
      
      Remainder of file ignored
      /tmp/pip-install-7m0qpibr/hexdump_fbb28ae931b94d22840dd6507c0b6b1f/setup.py:46: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
        from distutils.core import setup
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
      
      error: invalid command 'egg_info'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
*** Error 1
ModuleNotFoundError: No module named 'ltchiptool':
  File "/usr/local/lib/python3.11/dist-packages/platformio/builder/main.py", line 173:
    env.SConscript("$BUILD_SCRIPT")
  File "/data/cache/platformio/packages/tool-scons/scons-local-4.5.2/SCons/Script/SConscript.py", line 598:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/data/cache/platformio/packages/tool-scons/scons-local-4.5.2/SCons/Script/SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/data/cache/platformio/platforms/libretiny/builder/main.py", line 29:
    env.SConscript("utils/cores.py", exports="env")
  File "/data/cache/platformio/packages/tool-scons/scons-local-4.5.2/SCons/Script/SConscript.py", line 598:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/data/cache/platformio/packages/tool-scons/scons-local-4.5.2/SCons/Script/SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/data/cache/platformio/platforms/libretiny/builder/utils/cores.py", line 5:
    from ltchiptool import Family
========================= [FAILED] Took 15.10 seconds =========================
```

### Additional information

All worked correctly in ESPHome v.2023.11.4

Please note: cleaning build files does not help.

**Comment by elproko** [comment]
I played with following options:

esphome:
  name: ${name}
  friendly_name: "Techium BK"
**#  build_path: /config/esphome/techiumbk**

bk72xx:
  board: cb2s
  #generic-bk7231n-qfn32-tuya
  **framework:
    version: recommended**

After adding build_path, compiling with errors and next - removing it - compilation succeeded.
In the mean time I added also   **framework:    version: recommended** so I am not 100% sure which one actually fixed the issue.

Anyway - issue has gone so I am closing it.
