### ISSUE TITLE
Compile error on esp32-poe-iso

### ISSUE THREAD

**Issue by danielduerr** [esphome/issues#4179]
### The problem

Since the release of 2023.2.0, I am unable to compile esphome for my olimex poe esp32-poe-iso board.  The issue persists after upgrading to 2023.2.1.  And manually cleaning or completely removing the build directory makes no difference in outcome.  It always fails with the same error:

```Creating esp32 image...
Successfully created esp32 image.
Linking .pioenvs/olimex-bluetooth-proxy-06f82c/firmware.elf
/Users/dd/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/olimex-bluetooth-proxy-06f82c/src/esphome/components/ethernet/ethernet_component.o:(.literal._ZN7esphome8ethernet17EthernetComponent5setupEv+0x48): undefined reference to `esp_eth_phy_new_jl1101'
/Users/dd/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/olimex-bluetooth-proxy-06f82c/src/esphome/components/ethernet/ethernet_component.o: in function `esphome::ethernet::EthernetComponent::setup()':
/Users/dd/Sites/esphome/.esphome/build/olimex-bluetooth-proxy-06f82c/src/esphome/components/ethernet/ethernet_component.cpp:57: undefined reference to `esp_eth_phy_new_jl1101'
collect2: error: ld returned 1 exit status
*** [.pioenvs/olimex-bluetooth-proxy-06f82c/firmware.elf] Error 1
```

### Which version of ESPHome has the issue?

2023.2.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.2.4

### What platform are you using?

ESP32

### Board

esp32-poe-iso (olimex poe)

### Component causing the issue

ethernet/ethernet_component

### Anything in the logs that might be useful for us?

```txt
Creating esp32 image...
Successfully created esp32 image.
Linking .pioenvs/olimex-bluetooth-proxy-06f82c/firmware.elf
/Users/dd/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/olimex-bluetooth-proxy-06f82c/src/esphome/components/ethernet/ethernet_component.o:(.literal._ZN7esphome8ethernet17EthernetComponent5setupEv+0x48): undefined reference to `esp_eth_phy_new_jl1101'
/Users/dd/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/olimex-bluetooth-proxy-06f82c/src/esphome/components/ethernet/ethernet_component.o: in function `esphome::ethernet::EthernetComponent::setup()':
/Users/dd/Sites/esphome/.esphome/build/olimex-bluetooth-proxy-06f82c/src/esphome/components/ethernet/ethernet_component.cpp:57: undefined reference to `esp_eth_phy_new_jl1101'
collect2: error: ld returned 1 exit status
*** [.pioenvs/olimex-bluetooth-proxy-06f82c/firmware.elf] Error 1
```

### Additional information

[esphome compile log.txt](https://github.com/esphome/issues/files/10756036/esphome.compile.log.txt)

**Comment by nagyrobi** [comment]
Duplicate of https://github.com/esphome/issues/issues/4174
