### ISSUE TITLE
AttributeError: module 'esphome.components.font' has no attribute 'validate_pillow_installed' after update ESPHome 2024.12.0

### ISSUE THREAD

**Issue by MaxAu72** [esphome/issues#6571]
### The problem

After update ESPHome 2024.12.0 I received error: 
INFO ESPHome 2024.12.0
INFO Reading configuration /config/esphome/esphome-ulanzi-clock.yaml...
INFO Updating https://github.com/lubeda/EspHoMaTriXv2@main
WARNING 
WARNING This will only work with esphome >= 2023.7.0
WARNING Please check the documentation and wiki https://github.com/lubeda/EspHoMaTriXv2
WARNING 
ERROR Unable to load component ehmtxv2:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 177, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/external_components/e7db8eef/components/ehmtxv2/__init__.py", line 247, in <module>
    CONFIG_SCHEMA = cv.All(font.validate_pillow_installed, EHMTX_SCHEMA)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'esphome.components.font' has no attribute 'validate_pillow_installed'
Failed config

ehmtxv2: [source /config/esphome/esphome-ulanzi-clock.yaml:205]
  
  Component not found: ehmtxv2.
  id: rgb8x32
  icons2html: True
  matrix_component: ehmtx_display
  time_component: ehmtx_time
  time_format: %H:%M
  date_format: %d.%m.
  show_seconds: False
  show_date: True
  show_dow: True
  allow_empty_screen: False
  default_font_id: default_font
  default_font_yoffset: 8

### Which version of ESPHome has the issue?

ESPHome 2024.12.0

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2024.12.4

### What platform are you using?

ESP32

### Board

Ulanzi TC001

### Component causing the issue

ERROR Unable to load component ehmtxv2

### YAML Config

```yaml
ehmtxv2:
  id: rgb8x32
  icons2html: true
  matrix_component: ehmtx_display
  time_component: ehmtx_time
  time_format: "%H:%M"
  date_format: "%d.%m."
  show_seconds: false
  show_date: true
  show_dow: true
  allow_empty_screen: false
  default_font_id: default_font
  default_font_yoffset: 8
  special_font_id: special_font
  special_font_yoffset: 6
  # until here
  icons:
    - id: error
      lameid: 40530
    - id: home_assistant
      lameid: 47693
    - id: temperature
      lameid: 2056
    - id: lightbulb
      lameid: 1762
    - id: music
      lameid: 45625
    - id: phone
      lameid: 1232
    - id: car
      lameid: 2819
    - id: sleep8x32
      url: https://user-images.githubusercontent.com/16407309/224850723-634c9b2d-55d9-44f2-9f93-765c0485b090.gif
  on_next_screen:
    - homeassistant.event:
        event: esphome.new_screen
        data_template:
          iconname: !lambda "return icon.c_str();"
          text: !lambda "return text.c_str();"
```

### Additional information

With ESPHome 2024.11.3, it worked fine before upgrade.

**Comment by randybb** [comment]
this is not an esphome issue as it is an external component. For the fix check their github
https://github.com/lubeda/EspHoMaTriXv2/issues/261#issuecomment-2535874876
